ALTER TABLE app_settings
  ADD COLUMN IF NOT EXISTS pix_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS pix_merchant_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS pix_merchant_city TEXT NOT NULL DEFAULT '';
